### ISSUE TITLE
Repo cleaning

### ISSUE THREAD

**Issue by julibert** [micro-ROS/rmw-microxrcedds#37]
The following is a list of suggested actions to clean-up this repo:

- [x] rebase branches: [remove_unused_variable], [remove_duplicate_structs], [best_effort] and [6lowpan] over [dashing],
- [x] change #36 target branch to [dashing],
- [x] remove [master] and [migration] branches.

[migration]: https://github.com/micro-ROS/rmw-microxrcedds/tree/feature/dashing_migration
[dashing]: https://github.com/micro-ROS/rmw-microxrcedds/tree/dashing
[master]: https://github.com/micro-ROS/rmw-microxrcedds/tree/master
[remove_unused_variable]: https://github.com/micro-ROS/rmw-microxrcedds/tree/feature/remove_unused_variable
[remove_duplicate_structs]: https://github.com/micro-ROS/rmw-microxrcedds/tree/feature/remove_duplicated_structs
[best_effort]: https://github.com/micro-ROS/rmw-microxrcedds/tree/test/best_effort
[6lowpan]: https://github.com/micro-ROS/rmw-microxrcedds/tree/feature/6lowpan

**Comment by iluetkeb** [comment]
I changed the base on #36, but it also needs a re-base most likely.

- [ ]  rebase #36

**Comment by julibert** [comment]
Thanks @iluetkeb. Rebased!
