### ISSUE TITLE
undefined reference to `rosidl_typesupport_c__get_message_type_support_handle__std_msgs__msg__Int32'

### ISSUE THREAD

**Issue by Sdehnavi** [micro-ROS/rmw-microxrcedds#49]
Hi,
I am compiling micro-ROS crystal version and want to run the publisher demo for Int32. However, I get the following error:

> undefined reference to `rosidl_typesupport_c__get_message_type_support_handle__std_msgs__msg__Int32'"

It seems that this type is not defined.
Thanks

**Comment by pablogs9** [comment]
Please detail your use case and your environment
