### ISSUE TITLE
Use `uxr_nanos` from Micro-XRCE-DDS-Client instead of `clock_gettime` for random seed generation

### ISSUE THREAD

**Issue by driftregion** [micro-ROS/rmw-microxrcedds#72]
the platform-independence is already implemented in `uxr_nanos`

**Comment by pablogs9** [comment]
Closing since implemented: https://github.com/micro-ROS/rmw-microxrcedds/blob/b969cca2fa1a7d5e18e87996b9b82bef59837801/rmw_microxrcedds_c/src/rmw_init.c#L86
