### ISSUE TITLE
DDS-xrce over bluetooth

### ISSUE THREAD

**Issue by expploitt** [micro-ROS/rmw-microxrcedds#92]
Hello all!

I'm trying to configure a Bluetooth network but using DDS-XRCE and micro-ROS. Is that possible? I read the documentation but I'm not sure whether it is possible or not.

Thanks!

**Comment by pablogs9** [comment]
Hello sorry for the delayed response, have you checked the new external transports? https://micro.ros.org/docs/tutorials/advanced/create_custom_transports/
